Homework 1
Nerevarinka/2024-2-VK-EDU-Frontend-V-Konson pull request #1
Opened 2024-09-28 23:48 UTC by Nerevarinka

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor проверить его.

Что было сделано:
* Реализованы функции convertBytesToHuman, correctSentence и nonUniqueElements
* Написаны тесты для функции convertBytesToHuman

2024-09-30 16:21 UTC, nelkor requested changes

2024-09-30 16:21 UTC, nelkor commented on convertBytesToHuman.js
> +  if (typeof (bytes) != "number" || isNaN(bytes) || bytes < 0) {
Хорошо, что проверила на `NaN`, но это можно сократить с трёх проверок до двух.

```suggestion
  if (Number.isFinite(bytes) || bytes < 0) {
```

2024-09-30 16:21 UTC, nelkor commented on convertBytesToHuman.js
> +  const bytesInKB = 1024;
Константы (именно константы, а не константные переменные) называем в SCREAMING_SNAKE_CASE.

https://www.dev-notes.ru/articles/javascript/ten-js-naming-conventions-every-developer-should-know

2024-09-30 16:21 UTC, nelkor commented on convertBytesToHuman.test.js
Используй `describe` для создания группы тестов, а при помощи функции `test` создавай подгруппы. Например, подгруппу для валидных и невалидных аргументов.

2024-09-30 16:21 UTC, nelkor commented on correctSentence.test.js
> +test('returns correct sentence', () => {
Добавь проверки на невалидные значения.

2024-09-30 16:21 UTC, nelkor commented on nonUniqueElements.js
> +export function nonUniqueElements(data) {
Проверяй правильность аргумента в функции, а также добавь необходимые проверки в тесте.

2024-10-02 07:11 UTC, nelkor approved these changes

2024-10-02 13:34 UTC, merged

2024-10-02 13:34 UTC, martinkomitsky commented
12!